### ISSUE TITLE
Enable discussions

### ISSUE THREAD

**Issue by bbatsov** [emacsorphanage/adoc-mode#13]
They'd be useful to discuss potential improvements for `adoc-mode`. 

@tarsius Can you please do this? Seems I don't have the rights to do it.

**Comment by tarsius** [comment]
Done. I've also given you admin rights.

**Comment by bbatsov** [comment]
Thanks!

**Comment by tarsius** [comment]
By the way, if an experienced elisp developer is maintaining a package here (and has every intention to continue to do so, of course), then I prefer moving that package to the maintainer's account. How about it?

**Comment by bbatsov** [comment]
Well, I've been using the package for a very long time and at some point I planned to rewrite it when I saw it was going nowhere, so I guess you can count me in. :-) 

I don't promise that I'll actually find the time for the ambitious changes I had in mind, but I'll certainly keep the lights on and make sure we're `adoc-mode` is moving forward.

**Comment by tarsius** [comment]
That's certainly good enough with me. (That would also be good enough if a volunteer was less experienced, except in such cases it didn't actually work out enough times, for me to still prefer keeping things in the orphanage when the volunteer is less experienced.)

Since you have admin rights now, you should be able to transfer it yourself. (@TobiasZawada maintainer status should remain intact,as far as I know.)

Ping me when you are done, so that I can update the Melpa recipe.

**Comment by bbatsov** [comment]
Seems only org owners can do the transfer:

![image](https://user-images.githubusercontent.com/103882/186908151-01b53b25-6ff1-4e23-a9a7-c7a9b6610ea2.png)

**Comment by tarsius** [comment]
> You can only transfer a repository from an organization to yourself at this time

Ah. Great. (But why is there an input field, where I can input something else?)

Okay, done that. And then from there to you, which you have to accept. (I think you don't get a notification in the web ui, but you should get an email.)

**Comment by bbatsov** [comment]
Done!
